symbol = {
    'alpha': 'α',
    'beta': 'β',
    'gamma': 'γ',
    'lambda': 'λ',
    'plus': '+',
    'add': '+',
    'subtract': '-',
    'minus': '-',
    'into': '*',
    'multiply': 'X',
    'divide': '/',
    'by': '/',
    'percentage': '%',
    'mod': '%',
    'theta': 'θ',
    'integration': '∫',
    'derivative': '∂',
    'differentiation': '∂',
    'equal to': '=',
    'equals to': '=',
    'equas': '=',
    'limit': 'lim',
    'squared': '^2',
    'cubed': '^3',
    'square root': '√',
    'cube root': '∛',
    'power': '^',
    'phi': 'φ',
    'mixed fraction': '¾',
    'pi': 'π',
    'sigma': 'σ',
    'delta': 'δ',
    'epsilon': 'ε',
    'mu': 'μ',
    'nu': 'ν',
    'omicron': 'ο',
    'rho': 'ρ',
    'tau': 'τ',
    'upsilon': 'υ',
    'psi': 'ψ',
    'omega': 'ω',
    'greater than': '>',
    'less than': '<',
    'gtet': '≥',
    'ltet': '≤',
    'not equal to': '≠',
    'infinity': '∞',
    'integral': '∫',
    'partial': '∂',
    'degree': '°',
    'angle': '∠',
    'perpendicular': '⊥',
    'parallel': '∥',
}

def get():
    return symbol.copy()
